name: Python Greetings Delivery Pipeline

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        uses: ./.github/actions/install-pip-deps

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: install-pip-deps
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to Dev
        uses: ./.github/actions/deploy
        with:
          env: dev
          port: '7001'

  tests-on-dev:
    runs-on: ubuntu-latest
    needs: deploy-to-dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests on Dev
        uses: ./.github/actions/test
        with:
          env: dev

  # deploy-to-staging:
  #   runs-on: self-hosted
  #   needs: tests-on-dev
  #   steps:
  #     - name: Deploy to Staging
  #       uses: ./.github/actions/deploy
  #       with:
  #         env: staging
  #         port: '7002'

  # tests-on-staging:
  #   runs-on: self-hosted
  #   needs: deploy-to-staging
  #   steps:
  #     - name: Run tests on Staging
  #       uses: ./.github/actions/test
  #       with:
  #         env: staging

  # deploy-to-preprod:
  #   runs-on: self-hosted
  #   needs: tests-on-staging
  #   steps:
  #     - name: Deploy to Preprod
  #       uses: ./.github/actions/deploy
  #       with:
  #         env: preprod
  #         port: '7003'

  # tests-on-preprod:
  #   runs-on: self-hosted
  #   needs: deploy-to-preprod
  #   steps:
  #     - name: Run tests on Preprod
  #       uses: ./.github/actions/test
  #       with:
  #         env: preprod

  # deploy-to-prod:
  #   runs-on: self-hosted
  #   needs: tests-on-preprod
  #   steps:
  #     - name: Deploy to Prod
  #       uses: ./.github/actions/deploy
  #       with:
  #         env: prod
  #         port: '7004'

  # tests-on-prod:
  #   runs-on: self-hosted
  #   needs: deploy-to-prod
  #   steps:
  #     - name: Run tests on Prod
  #       uses: ./.github/actions/test
  #       with:
  #         env: prod
